FROM node:24-alpine AS build

WORKDIR /app

COPY package.json package-lock.json* ./
COPY src/plugins/iconify ./src/plugins/iconify

RUN npm i

COPY . .
COPY .env.staging .env

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

# docker run -d -p 8080:80 --name myapp_staging myapp:staging